ci:
  skip: [pylint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.1
    hooks:
      - id: autoflake
        exclude: &fixtures tests/functional/
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.0.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
        exclude: *fixtures
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: *fixtures
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--quiet]
        exclude: *fixtures
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.10.1]
        exclude: *fixtures
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["--disable=import-error, cyclic-import", "--load-plugins=pylint_pytest_plugin"]
        exclude: *fixtures
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
      - id: mypy
        args: [--config-file=pyproject.toml]
        exclude: *fixtures
        additional_dependencies:
          [pytest-stub==1.1.0]
  - repo: https://github.com/DanielNoord/pydocstringformatter
    rev: v0.7.2
    hooks:
      - id: pydocstringformatter
        args: ["--linewrap-full-docstring"]
